# catch all goal
all:


TOP = $(TOPDIR)/top
BT1 = $(TOPDIR)/bottom1 
BT2 = $(TOPDIR)/bottom2

AUXSRC = $(TOP) $(BT1) $(BT2)

%.html: %.thtml $(AUXSRC)
	@cat $(TOP) $< $(BT1)   > $@
	@echo "<div>$(shell date '+Updated on %d-%m-%Y')</div>" >> $@
	@cat $(BT2) >> $@
	@echo HTML $@








.PHONY: $(SUBDIRS) all clean
all: Makefile $(SUBDIRS)
clean: $(SUBDIRS)

$(SUBDIRS):
	$(MAKE) -C $@ $(MAKECMDGOALS)

clean:
	$(RM) *.html *~