#!/bin/sh
#
#/usr/bin/gdm-control --shutdown && openbox --exit
exec dbus-send --system --print-reply --dest=org.freedesktop.ConsoleKit /org/freedesktop/ConsoleKit/Manager org.freedesktop.ConsoleKit.Manager.Stop
