## miniconf makefiles ## 1.1 ##

TOPDIR := ../..

batterytext_src = batterytext.c
batterytext_cflags = -DPLUGIN $(GTK2_CFLAGS) 
batterytext_libs = $(GTK2_LIBS) 
batterytext_type = lib 

include $(TOPDIR)/.config/rules.mk
