## miniconf makefiles ## 1.1 ##

TOPDIR := ../..

taskbar_src = taskbar.c
taskbar_cflags = -DPLUGIN $(GTK2_CFLAGS) 
taskbar_libs = $(GTK2_LIBS) 
taskbar_type = lib 

include $(TOPDIR)/.config/rules.mk
