## miniconf makefiles ## 1.1 ##

TOPDIR := ../..

launchbar_src = launchbar.c
launchbar_cflags = -DPLUGIN $(GTK2_CFLAGS) 
launchbar_libs = $(GTK2_LIBS) 
launchbar_type = lib 

include $(TOPDIR)/.config/rules.mk
