## miniconf makefiles ## 1.1 ##

TOPDIR := ../..

separator_src = separator.c
separator_cflags = -DPLUGIN $(GTK2_CFLAGS) 
separator_libs = $(GTK2_LIBS) 
separator_type = lib 

include $(TOPDIR)/.config/rules.mk
