## miniconf makefiles ## 1.1 ##

TOPDIR := ../..

menu_src = menu.c \
    system_menu.c
menu_cflags = -DPLUGIN $(GTK2_CFLAGS) 
menu_libs = $(GTK2_LIBS) 
menu_type = lib 

include $(TOPDIR)/.config/rules.mk
